### PR TITLE
Add ability to create slides with custom HTML content.

### PR DESCRIPTION
**Pull request by urbantrout**
Solves https://github.com/GuoQichen/vue-pswipe/issues/15

### CODE REVIEW

**Comment by GuoQichen** [comment]
Actually, putting `html` in `dataset` is not appropriate. I plan to provide an API like `this.$ Pswp.createPswp ({html: ''))`.

**Comment by urbantrout** [comment]
Using dataset for HTML is definitely not the best way. I have to escape quotes and stuff to make it work.
But that's what PhotoSwipe docs suggested.

I am looking forward to your solution.

**Comment by edoaxyz** [comment]
@GuoQichen Why not keeping both solutions? The `$Pswp.open` method doesn't grab automatically all the images in gallery and does not reproduce the same animations around the initial frame.

**Comment by GuoQichen** [comment]
@edoaxyz 
The animation of first frame is designed for pictures, not suitable for custom HTML content. Putting a lot of HTML fragments in HTML attributes is not a suitable solution either. If you need to get all the pictures, you can manually parse the HTML to get all the img tags.

**Pull request closed without merging**
